import "dotenv/config";
import { db } from "./index";
import { corridors, providers, transfers, auditLogs, walletState } from "./schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  // Check if corridors already exist
  const existingCorridors = await db.select().from(corridors);
  if (existingCorridors.length > 0) {
    return;
  }

  console.log("Seeding initial PollarBridge data...");

  // 1. Corridors
  await db.insert(corridors).values([
    {
      id: "NG-BOB",
      fromCountry: "Nigeria",
      fromCode: "NG",
      fromCurrency: "NGN",
      toCountry: "Bolivia",
      toCode: "BO",
      toCurrency: "BOB",
      usdcRate: "1608.2000",
      bobPerUsdc: "6.9600",
      minAmount: "5000.00",
      maxAmount: "5000000.00",
      status: "ACTIVE",
      description: "Direct Nigerian local payment rails to Bolivian USDC & local payout",
      settlementSpeed: "5-15 min",
    },
    {
      id: "GH-BOB",
      fromCountry: "Ghana",
      fromCode: "GH",
      fromCurrency: "GHS",
      toCountry: "Bolivia",
      toCode: "BO",
      toCurrency: "BOB",
      usdcRate: "15.4200",
      bobPerUsdc: "6.9600",
      minAmount: "100.00",
      maxAmount: "50000.00",
      status: "ACTIVE",
      description: "Ghana Mobile Money (MTN, Telecel, AT) to Bolivia USDC settlement",
      settlementSpeed: "5-10 min",
    },
    {
      id: "KE-BOB",
      fromCountry: "Kenya",
      fromCode: "KE",
      fromCurrency: "KES",
      toCountry: "Bolivia",
      toCode: "BO",
      toCurrency: "BOB",
      usdcRate: "129.5000",
      bobPerUsdc: "6.9600",
      minAmount: "1000.00",
      maxAmount: "250000.00",
      status: "COMING_SOON",
      description: "Kenya M-Pesa automated Daraja bridge to Bolivia payout",
      settlementSpeed: "Instant",
    },
    {
      id: "ZA-BOB",
      fromCountry: "South Africa",
      fromCode: "ZA",
      fromCurrency: "ZAR",
      toCountry: "Bolivia",
      toCode: "BO",
      toCurrency: "BOB",
      usdcRate: "18.2500",
      bobPerUsdc: "6.9600",
      minAmount: "200.00",
      maxAmount: "100000.00",
      status: "ACTIVE",
      description: "South Africa Capitec & Instant EFT to Bolivia Pollar USDC bridge",
      settlementSpeed: "10-25 min",
    },
  ]);

  // 2. Providers
  await db.insert(providers).values([
    {
      id: "demo_ng_bank",
      name: "Demo Bank (PollarBridge Sandbox)",
      corridorId: "NG-BOB",
      railType: "Bank transfer",
      mode: "Sandbox",
      status: "Healthy",
      estimatedDelivery: "10–20 minutes",
      fixedFee: "700.00",
      percentFee: "0.0000",
      speedRank: "Cheapest",
      verificationMethod: "Operator sandbox manual",
      bankName: "PollarBridge Sandbox Bank",
      accountNumber: "0123456789",
      accountName: "PollarBridge Africa Escrow",
      totalCalls: 182,
      errorRate: "0.00",
    },
    {
      id: "demo_ng_p2p",
      name: "Demo Liquidity Agent (P2P)",
      corridorId: "NG-BOB",
      railType: "P2P Provider",
      mode: "Sandbox",
      status: "Healthy",
      estimatedDelivery: "2–5 minutes",
      fixedFee: "1200.00",
      percentFee: "0.0000",
      speedRank: "Fastest",
      verificationMethod: "Manual verification",
      bankName: "Kuda Microfinance Desk",
      accountNumber: "2098451120",
      accountName: "Demo P2P Agent - Chinedu",
      totalCalls: 145,
      errorRate: "0.00",
    },
    {
      id: "sandbox_gh_momo",
      name: "Sandbox Mobile Money (MTN / Telecel)",
      corridorId: "GH-BOB",
      railType: "Mobile money",
      mode: "Sandbox",
      status: "Healthy",
      estimatedDelivery: "5–10 minutes",
      fixedFee: "15.00",
      percentFee: "0.0050",
      speedRank: "Cheapest",
      verificationMethod: "Automated webhook simulation",
      bankName: "MTN Mobile Money Ghana",
      accountNumber: "+233 24 555 0192",
      accountName: "PollarBridge Ghana Merchant",
      totalCalls: 96,
      errorRate: "2.10",
    },
    {
      id: "live_ng_bank",
      name: "NG Live Bank Rail (NIP Switch)",
      corridorId: "NG-BOB",
      railType: "Bank transfer",
      mode: "Live",
      status: "Locked",
      estimatedDelivery: "1–5 minutes",
      fixedFee: "1000.00",
      percentFee: "0.0020",
      speedRank: "Standard",
      verificationMethod: "Automated NIBSS NIP Settlement",
      bankName: "Zenith Bank Commercial",
      accountNumber: "1019284729",
      accountName: "PollarBridge Technologies Ltd",
      totalCalls: 0,
      errorRate: "0.00",
    },
    {
      id: "sandbox_za_eft",
      name: "Sandbox Ozow / Instant EFT",
      corridorId: "ZA-BOB",
      railType: "Bank transfer",
      mode: "Sandbox",
      status: "Healthy",
      estimatedDelivery: "10–15 minutes",
      fixedFee: "25.00",
      percentFee: "0.0040",
      speedRank: "Cheapest",
      verificationMethod: "Instant EFT Sandbox Webhook",
      bankName: "Standard Bank SA",
      accountNumber: "401928401",
      accountName: "PollarBridge SA PTY",
      totalCalls: 64,
      errorRate: "0.00",
    },
  ]);

  // 3. Wallet State
  await db.insert(walletState).values({
    id: "primary_pollar_wallet",
    address: "GDQP2KPQGKIHYJGXNURG74YTI5FD5CJXNURG74YTI5FD5C",
    usdcBalance: "1850.4500",
    xlmBalance: "48.2000",
    network: "Stellar Testnet",
  });

  // 4. Initial Transfers for realistic demo experience
  const now = new Date();
  const expires = new Date(now.getTime() + 15 * 60 * 1000);

  // Transfer 1: PB-NG-20481 (as referenced in instructions)
  await db.insert(transfers).values([
    {
      id: "PB-NG-20481",
      trackingToken: "track_pb_ng_20481_sec902",
      senderName: "Adekunle Olumide",
      senderEmail: "adekunle@example.com",
      sourceCountry: "Nigeria",
      sourceCurrency: "NGN",
      destCountry: "Bolivia",
      destCurrency: "BOB",
      sourceAmount: "100000.00",
      providerFee: "800.00",
      pollarFee: "700.00",
      totalSourceAmount: "101500.00",
      usdcAmount: "62.1800",
      estimatedBobPayout: "172.00",
      exchangeRate: "1608.2000",
      selectedRailId: "demo_ng_bank",
      railName: "Demo Bank (PollarBridge Sandbox)",
      status: "PAYMENT_DETECTED", // in review in queue
      paymentReference: "PB-NG-20481",
      recipientWalletAddress: "GDQP2KPQGKIHYJGXNURG74YTI5FD5CJXNURG74YTI5FD5C",
      recipientName: "Maria Rodriguez",
      paymentProofUrl: "https://pollarbridge.africa/proofs/pb-ng-20481-bankslip.pdf",
      operatorNotes: "Local payment detected via Sandbox Bank. Awaiting operator verification before USDC release.",
      pollarTxHash: null,
      stellarLedger: null,
      rateSource: "Simulated sandbox rate",
      quoteExpiresAt: expires,
      paidAt: new Date(now.getTime() - 12 * 60 * 1000),
      reconciled: false,
      actualPaidAmount: "101500.00",
      createdAt: new Date(now.getTime() - 25 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 12 * 60 * 1000),
    },
    {
      id: "PB-NG-20478",
      trackingToken: "track_pb_ng_20478_x89a",
      senderName: "Chioma Okeke",
      senderEmail: "chioma@example.com",
      sourceCountry: "Nigeria",
      sourceCurrency: "NGN",
      destCountry: "Bolivia",
      destCurrency: "BOB",
      sourceAmount: "250000.00",
      providerFee: "1200.00",
      pollarFee: "1750.00",
      totalSourceAmount: "252950.00",
      usdcAmount: "155.4500",
      estimatedBobPayout: "430.00",
      exchangeRate: "1608.2000",
      selectedRailId: "demo_ng_p2p",
      railName: "Demo Liquidity Agent (P2P)",
      status: "COMPLETED",
      paymentReference: "PB-NG-20478",
      recipientWalletAddress: "GBV47J2D3Z2P7QXZ5N9VTR3B4C5D6E7F8G9H0J1K2L3M",
      recipientName: "Carlos Mamani",
      paymentProofUrl: "https://pollarbridge.africa/proofs/p2p-screenshot-chioma.png",
      operatorNotes: "P2P confirmation verified. Settled on Stellar testnet.",
      pollarTxHash: "8b7c91e2f044a1b8c34f37829104041b6c7a91e2049281a8b9c1d2e3f4",
      stellarLedger: "4829104",
      rateSource: "Simulated sandbox rate",
      quoteExpiresAt: new Date(now.getTime() - 120 * 60 * 1000),
      paidAt: new Date(now.getTime() - 100 * 60 * 1000),
      verifiedAt: new Date(now.getTime() - 95 * 60 * 1000),
      settledAt: new Date(now.getTime() - 90 * 60 * 1000),
      reconciled: true,
      actualPaidAmount: "252950.00",
      createdAt: new Date(now.getTime() - 120 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 90 * 60 * 1000),
    },
    {
      id: "PB-GH-10902",
      trackingToken: "track_pb_gh_10902_momo",
      senderName: "Kwame Mensah",
      senderEmail: "kwame@example.com",
      sourceCountry: "Ghana",
      sourceCurrency: "GHS",
      destCountry: "Bolivia",
      destCurrency: "BOB",
      sourceAmount: "1500.00",
      providerFee: "22.50",
      pollarFee: "15.00",
      totalSourceAmount: "1537.50",
      usdcAmount: "97.2800",
      estimatedBobPayout: "269.00",
      exchangeRate: "15.4200",
      selectedRailId: "sandbox_gh_momo",
      railName: "Sandbox Mobile Money (MTN)",
      status: "IN_REVIEW",
      paymentReference: "PB-GH-10902",
      recipientWalletAddress: "GC7R2X3Y4Z5W6V7U8T9S0R1Q2P3O4N5M6L7K8J9I",
      recipientName: "Sofia Flores",
      paymentProofUrl: "https://pollarbridge.africa/proofs/mtn-momo-sms-proof.png",
      operatorNotes: "Mobile money prompt accepted by sender. Under final operator signoff.",
      pollarTxHash: null,
      stellarLedger: null,
      rateSource: "Simulated sandbox rate",
      quoteExpiresAt: expires,
      paidAt: new Date(now.getTime() - 5 * 60 * 1000),
      reconciled: false,
      actualPaidAmount: "1537.50",
      createdAt: new Date(now.getTime() - 10 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 5 * 60 * 1000),
    },
    {
      id: "PB-ZA-30114",
      trackingToken: "track_pb_za_30114_eft",
      senderName: "Sipho Dlamini",
      senderEmail: "sipho@example.com",
      sourceCountry: "South Africa",
      sourceCurrency: "ZAR",
      destCountry: "Bolivia",
      destCurrency: "BOB",
      sourceAmount: "3000.00",
      providerFee: "37.00",
      pollarFee: "30.00",
      totalSourceAmount: "3067.00",
      usdcAmount: "164.3800",
      estimatedBobPayout: "455.00",
      exchangeRate: "18.2500",
      selectedRailId: "sandbox_za_eft",
      railName: "Sandbox Ozow / Instant EFT",
      status: "COMPLETED",
      paymentReference: "PB-ZA-30114",
      recipientWalletAddress: "GDM6X9P2K3N4J5H6G7F8D9S0A1Q2W3E4R5T6Y7U8",
      recipientName: "Alejandro Quispe",
      paymentProofUrl: "https://pollarbridge.africa/proofs/ozow-receipt-30114.pdf",
      operatorNotes: "Instant EFT cleared automatically and verified.",
      pollarTxHash: "4f2a71b9c032a7e5d89b1426374950e1837492cfa712e9b08492038172",
      stellarLedger: "4828950",
      rateSource: "Simulated sandbox rate",
      quoteExpiresAt: new Date(now.getTime() - 300 * 60 * 1000),
      paidAt: new Date(now.getTime() - 280 * 60 * 1000),
      verifiedAt: new Date(now.getTime() - 275 * 60 * 1000),
      settledAt: new Date(now.getTime() - 270 * 60 * 1000),
      reconciled: true,
      actualPaidAmount: "3067.00",
      createdAt: new Date(now.getTime() - 300 * 60 * 1000),
      updatedAt: new Date(now.getTime() - 270 * 60 * 1000),
    },
  ]);

  // 5. Initial Audit Logs
  await db.insert(auditLogs).values([
    {
      id: "log_1",
      transferId: "PB-NG-20481",
      actor: "Sender",
      action: "QUOTE_GENERATED",
      details: "Quote generated for 100,000 NGN -> 62.18 USDC (Rate 1608.20 NGN/USDC)",
      createdAt: new Date(now.getTime() - 25 * 60 * 1000),
    },
    {
      id: "log_2",
      transferId: "PB-NG-20481",
      actor: "Sender",
      action: "PAYMENT_SUBMITTED",
      details: "Sender submitted payment notification with bank slip reference PB-NG-20481",
      createdAt: new Date(now.getTime() - 12 * 60 * 1000),
    },
    {
      id: "log_3",
      transferId: "PB-NG-20478",
      actor: "Operator",
      action: "PAYMENT_VERIFIED",
      details: "Operator verified incoming 252,950 NGN via Kuda P2P Desk. Verification approved.",
      createdAt: new Date(now.getTime() - 95 * 60 * 1000),
    },
    {
      id: "log_4",
      transferId: "PB-NG-20478",
      actor: "Pollar Engine",
      action: "USDC_MINTED",
      details: "Pollar Testnet settled 155.45 USDC to recipient wallet. Tx: 8b7c91e2...a8b9",
      createdAt: new Date(now.getTime() - 90 * 60 * 1000),
    },
  ]);

  console.log("Database seeded successfully.");
}

if (process.env.RUN_SEED === "true") {
  seedDatabase()
    .then(() => {
      console.log("Seed complete.");
      process.exit(0);
    })
    .catch((err) => {
      console.error("Seed error:", err);
      process.exit(1);
    });
}
